#!/bin/bash
set -e

stages=$(cat ./pipelines/deploy-infra.yml | grep -oP 'stage: \K\w+')
echo $stages

backendTemplate=$(<.azure/backendTemplate.tf)
  
for count in "${!stages[@]}"; do
    stage=${stages[$count]}

    pushd ./$stage > /dev/null
    for d in */ ; do
        if [[ $d == "*/" ]]; then
            break
        fi
        group=$(echo "$d" | sed 's/\///g' | sed 's/ /_/g')

        backendConfigFile="./${group}/backend.tf"
        echo $backendConfigFile
        echo "$backendTemplate" | sed "s/{{.GroupName}}/$group/g" > "$backendConfigFile"
        git add $backendConfigFile
    done
    popd > /dev/null
done
