#!/bin/bash
set -e

readarray -t stages < <(grep -oP 'stage: \K\w+' ./.pipelines/deploy-infra.yml)

backendTemplate=$(<.azure/backendTemplate.tf)
  
for count in "${!stages[@]}"; do
    stage=${stages[$count]}

    pushd ./$stage > /dev/null
    for d in */ ; do
        if [[ $d == "*/" ]]; then
            break
        fi
        group=$(echo "$d" | sed 's/\///g' | sed 's/ /_/g')

        backendConfigFile="./${group}/backend.tf"
        echo "update backend file $backendConfigFile"
        echo "$backendTemplate" | sed "s/{{.GroupName}}/$group/g" > "$backendConfigFile"
        git add $backendConfigFile
    done
    popd > /dev/null
done
