name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(DayOfYear)$(Rev:r)

trigger:
  branches:
    include:
    - main

pool: <your_pool_name> # TODO: Change this to your pool name

stages:
  - stage: dev
    jobs:
    - template: templates/list-and-run.yml
      parameters:
        directory: dev
  - stage: qa
    jobs:
    - template: templates/list-and-run.yml
      parameters:
        directory: qa
  - stage: prod
    jobs:
    - template: templates/list-and-run.yml
      parameters:
        directory: prod
